MvcApplication1/Areas/Admin/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Llprk.DataAccess.Models;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure;
using System.Configuration;
using System.IO;
using Llprk.Web.UI.Controllers;
using Llprk.Web.UI.Areas.Admin.Models;

namespace Llprk.Web.UI.Areas.Admin.Controllers
{
    [Authorize]
    public partial class PicturesController : ApplicationController
    {
        //
        // GET: /Pictures/

        public virtual ActionResult Index()
        {
            return View(db.Pictures.OrderBy(p => p.Name).ToList());
        }

        //
        // GET: /Pictures/Details/5

        public virtual ActionResult Details(Guid id)
        {
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        //
        // GET: /Pictures/Create

        public virtual ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Pictures/Create

        [HttpPost]
        public virtual ActionResult Create(IEnumerable<HttpPostedFileBase> files)
        {
            if (files == null || files.Count() == 0) {
                ModelState.AddModelError("Picture", "You need to select at least one picture!");
            }
            else
            {
                foreach (var file in files) {
                    if (file != null && file.ContentLength > 0) {
                        _RequestToPicture(file);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return Redirect("index");
        }

        //
        // GET: /Pictures/Delete/5
        public virtual ActionResult Delete(Guid id)
        {
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }

            return View(new PictureDelete() {
                Picture = picture,
                Products = from p in db.Products
                           where p.Pictures.Any(pi => pi.Id == picture.Id)
                           select p
            });
        }

        //
        // POST: /Pictures/Delete/5

        [HttpPost, ActionName("Delete")]
        public virtual ActionResult DeleteConfirmed(Guid id)
        {
            Picture picture = db.Pictures.Find(id);
            
            // Remove Picture from Blob Storage
            var storageAccount = _getStorageAccount();

            var blobClient = storageAccount.CreateCloudBlobClient();
#if DEBUG
            var container = blobClient.GetContainerReference("picturestest");
#else
            var container = blobClient.GetContainerReference("pictures");
#endif

            // Erst die Bilder aus der DB löschen...
            db.Pictures.Remove(picture);
            db.SaveChanges();

            // ...und dann vom Blob-Storage.
            var blob = container.GetBlockBlobReference(picture.Id.ToString()+".png");
            blob.DeleteIfExists();
            blob = container.GetBlockBlobReference(picture.Id.ToString() + "_t.png");
            blob.DeleteIfExists();
            
            return RedirectToAction("Index");
        }


        /// <summary>
        /// Bild auf Blob-Storage hochladen.
        /// </summary>
        /// <param name="data"></param>
        /// <param name="name"></param>
        /// <param name="container"></param>
        private static void _PutPicture(Stream data, string name, Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer container)
        {
            var blob = container.GetBlockBlobReference(name + ".png");
            data.Seek(0, SeekOrigin.Begin);
            blob.UploadFromStream(data);
        }

        /// <summary>
        /// Bild verkleinern und dabei die Seitenverhältnisse beibehalten.
        /// </summary>
        /// <param name="inStream"></param>
        /// <param name="outStream"></param>
        /// <param name="width">Maximale Höhe</param>
        /// <param name="height">Maximale Breite</param>
        private void _ResizePictures(Stream inStream, MemoryStream outStream, int width, int height)
        {
            using (var src = Image.FromStream(inStream))
            {
                // Proportionen beibehalten.
                var ratioX = width / (double)src.Width;
                var ratioY = height / (double)src.Height;
                var ratio = Math.Min(ratioX, ratioY);
                var newWidth = (int)(src.Width * ratio);
                var newHeight = (int)(src.Height * ratio);
                var moveX = (width - newWidth) / 2;
                var moveY = (height - newHeight) / 2;

                using (var dst = new Bitmap(width, height))
                {
                    using (var g = Graphics.FromImage(dst))
                    {
                        g.SmoothingMode = SmoothingMode.AntiAlias;
                        g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                        g.DrawImage(src, moveX, moveY, newWidth, newHeight);
                    }

                    dst.Save(outStream, ImageFormat.Png);
                }
            }
        }

        /// <summary>
        /// Von einem hochgeladenen File, Bild und Thumbnail speichern.
        /// </summary>
        /// <param name="file"></param>
        private void _RequestToPicture(HttpPostedFileBase file)
        {
            var thumbnailStream = new MemoryStream();
            var resizedStream = new MemoryStream();

            _ResizePictures(file.InputStream, resizedStream, 400, 400);
            _ResizePictures(file.InputStream, thumbnailStream, 100, 100);

            var picture = new Picture() {
                Id = Guid.NewGuid(),
                Name = Path.GetFileName(file.FileName)
            };

            var storageAccount = _getStorageAccount();

            var blobClient = storageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("pictures");
            _PutPicture(resizedStream, picture.Id.ToString(), container);
            _PutPicture(thumbnailStream, picture.Id.ToString() + "_t", container);

            db.Pictures.Add(picture);
        }

		/// <summary>
		/// 
		/// </summary>
		/// <returns></returns>
        private static CloudStorageAccount _getStorageAccount()
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(
                ConfigurationManager.AppSettings["StorageConnection"]);
            return storageAccount;
        }
    }
}

MvcApplication1/Areas/Admin/Controllers/api/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Llprk.DataAccess.Models;

namespace Llprk.Web.UI.Areas.Admin.Controllers.api
{
    public class PicturesController : ApiController
    {
        private Entities db = new Entities();

        // GET api/Pictures
        public IEnumerable<Picture> GetPictures()
        {
            return db.Pictures.AsEnumerable();
        }

        // GET api/Pictures/5
        public Picture GetPicture(Guid id)
        {
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return picture;
        }

        // PUT api/Pictures/5
        public HttpResponseMessage PutPicture(Guid id, Picture picture)
        {
            if (ModelState.IsValid && id == picture.Id)
            {
                db.Entry(picture).State = EntityState.Modified;

                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return Request.CreateResponse(HttpStatusCode.NotFound);
                }

                return Request.CreateResponse(HttpStatusCode.OK);
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        // POST api/Pictures
        public HttpResponseMessage PostPicture(Picture picture)
        {
            if (ModelState.IsValid)
            {
                db.Pictures.Add(picture);
                db.SaveChanges();

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.Created, picture);
                response.Headers.Location = new Uri(Url.Link("DefaultApi", new { id = picture.Id }));
                return response;
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        // DELETE api/Pictures/5
        public HttpResponseMessage DeletePicture(Guid id)
        {
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            db.Pictures.Remove(picture);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            return Request.CreateResponse(HttpStatusCode.OK, picture);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication1/Areas/Admin/Views/Pictures/Create.cshtml
@model Llprk.DataAccess.Models.Picture

@{
    ViewBag.Title = "Create";
}

<div class="col-xs-12">
    @using (Html.BeginForm("Create", "Pictures", FormMethod.Post, new { enctype = "multipart/form-data" })) {
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Add Picture</legend>

            <div class="controls">
                <input type="file" name="files" multiple />
            </div>

            <div class="form-actions">
                <input type="submit" value="Create" class="btn btn-small btn-success" />
                <small class="muted">or</small>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </fieldset>
    }

    <div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Areas/Admin/Views/Pictures/Delete.cshtml
@model Llprk.Web.UI.Areas.Admin.Models.PictureDelete

@{
    ViewBag.Title = "Delete";

    var deleteDisabled = Model.Products.Count() > 0 ? "disabled" : null;
}


<div class="col-xs-12">
    @using (Html.BeginForm()) {
        <fieldset>
            <legend>Are you sure you want to delete this?<span class="badge">@Model.Products.Count()</span></legend>
            <img src="@Model.Picture.PictureUrl" />
            <div class="control-group">
                @if(Model.Products.Count() > 0) {
                    <legend>Products that use this picture:</legend>
                    <label class="control-label">Used in</label>
                    <div class="controls">
                        <ul>
                            @foreach (var p in Model.Products) {
                                <li>
                                    @Html.ActionLink(p.Name, "edit", "products", new {id=p.Id}, null)
                                </li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </fieldset>
        <div class="form-actions">
            <input type="submit" value="Delete" class="btn btn-small btn-danger @deleteDisabled" @deleteDisabled />
            <small class="muted">or</small>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcApplication1/Areas/Admin/Views/Pictures/Details.cshtml
@model Llprk.DataAccess.Models.Picture

@{
    ViewBag.Title = "Details";
}

<h2>@Model.Name</h2>
<img src="@Model.PictureUrl" />

<fieldset>
    <legend>Picture</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcApplication1/Areas/Admin/Views/Pictures/Edit.cshtml
@model Llprk.DataAccess.Models.Picture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Picture</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Save" class="btn" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Areas/Admin/Views/Pictures/Index.cshtml
@model IEnumerable<Llprk.DataAccess.Models.Picture>

@{
    ViewBag.Title = "Index";
}

<div class="col-xs-12">
    <div class="buttons">
        @Html.ActionLink("Add Picture", "Create", null, new { @class="btn btn-small btn-success" })
    </div>
    <ul class="thumbnails">
        @foreach (var item in Model)
        {
            <li class="span2">
                <div class="img-polaroid">
                    <img src="@item.ThumbnailUrl" />
                    <a href="@Url.Action("delete", new { id = item.Id })"><i class="icon-trash"></i></a>
                </div>
                <small class="muted">@item.Name&nbsp;</small>
            </li>
        }
    </ul>
</div>